name: Test Project
on:
  release:
    types: [published]
env:
  ecr_repo: mymove-concierge
  # ecr_repo : ${{ contains(github.ref,'refs/tags/cron') && 'refs/tags/cron' || 'mymove-concierge' }}
jobs:
  process_inputs:
    name: process_cron
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && ${{ startsWith(github.ref, 'refs/tags/cron') }}
    steps:
      - name: print initial
        run: echo "$ecr_repo"
      - name: Set env
        run: echo "ecr_repo=mymove-cron" >> $GITHUB_ENV
      - name: print env
        run: echo "$ecr_repo"
      - name: print
        run: echo "${{ github.ref }}"