name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latests
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Run tests
        run: npm test
  deploy:
    needs: [test]
    runs-on: ubuntu-lastest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Build project
        run: echo "Deploying ..."